### PR TITLE
WIP: add readlink and test.lua, add sym-link directory/file support to ls()

### PR DESCRIPTION
**Pull request by konsumer**
This adds `readlink` to API (for non-windows) and resolves links in `ls` to determine if they are file/directory. This will allow file-browsers in linux/osx that support sym-links.

I also added luajit support (put a condition branch around only use of love for `home`) and made a  little test-file for myself, so I could ensure it was working right in luajit, quickly.

Related: #2 

```
luajit test.lua

boot/
config/
dev/
etc/
home/
keybase/
lost+found/
media/
mnt/
opt/
proc/
recovery/
root/
run/
snap/
srv/
storage/
sys/
testlinkdir/
tmp/
usr/
var/
bin
lib
lib32
lib64
libx32
sbin
testlinkfile


From this:

total 92
drwxr-xr-x  23 root     root  4096 Jul 31 13:24 .
drwxr-xr-x  23 root     root  4096 Jul 31 13:24 ..
lrwxrwxrwx   1 root     root     7 Apr  3 08:00 bin -> usr/bin
drwxr-xr-x   3 root     root  4096 Jul  6 00:07 boot
drwxr-xr-x   2 root     root  4096 Jun 19 15:36 config
drwxr-xr-x  20 root     root  5080 Jul 29 19:12 dev
drwxr-xr-x 154 root     root 12288 Jul 30 22:34 etc
drwxr-xr-x   3 root     root  4096 Jun 18 17:09 home
dr-xr-xr-x   1 root     root     0 Jul 29 19:37 keybase
lrwxrwxrwx   1 root     root     7 Apr  3 08:00 lib -> usr/lib
lrwxrwxrwx   1 root     root     9 Apr  3 08:00 lib32 -> usr/lib32
lrwxrwxrwx   1 root     root     9 Apr  3 08:00 lib64 -> usr/lib64
lrwxrwxrwx   1 root     root    10 Apr  3 08:00 libx32 -> usr/libx32
drwx------   2 root     root 16384 Jun 18 17:01 lost+found
drwxr-xr-x   3 root     root  4096 Jun 18 17:11 media
drwxr-xr-x   2 root     root  4096 Apr  3 08:00 mnt
drwxr-xr-x   7 root     root  4096 Jul 15 22:42 opt
dr-xr-xr-x 412 root     root     0 Jul 29 19:12 proc
drwx------   8 root     root  4096 Dec 31  1969 recovery
drwx------   6 root     root  4096 Jul 31 13:23 root
drwxr-xr-x  37 root     root  1140 Jul 30 13:27 run
lrwxrwxrwx   1 root     root     8 Apr  3 08:00 sbin -> usr/sbin
drwxr-xr-x   6 root     root  4096 Jul 23 17:48 snap
drwxr-xr-x   2 root     root  4096 Apr  3 08:00 srv
drwxr-xr-x   9 konsumer root  4096 Jul 18 02:50 storage
dr-xr-xr-x  13 root     root     0 Jul 29 19:12 sys
lrwxrwxrwx   1 root     root     4 Jul 31 13:24 testlinkdir -> etc/
lrwxrwxrwx   1 root     root    15 Jul 31 13:24 testlinkfile -> etc/resolv.conf
drwxrwxrwt  30 root     root  4096 Jul 31 13:27 tmp
drwxr-xr-x  14 root     root  4096 Jun 17 12:49 usr
drwxr-xr-x  14 root     root  4096 Jul 23 17:46 var
```

Many of these directories are actually sym-links.

Everything is the same, API-wise, symlinks are just added to files/dirs, and there is a new `readlink` function users can use.

### CODE REVIEW

**Comment by konsumer** [comment]
I still need to look closer at this. `isDirectory` causes recursion (it uses `ls`) and so I need a better method of determining if it's a directory. The current method of looking for `/` only works for sym-links that actually have `/` in the target.

In this, `/sbin` should be a dir, for example:

```
boot/
config/
dev/
etc/
home/
keybase/
lost+found/
media/
mnt/
opt/
proc/
recovery/
root/
run/
snap/
srv/
storage/
sys/
testlinkdir/
tmp/
usr/
var/
bin
lib
lib32
lib64
libx32
sbin
testlinkfile


From this:

total 92
drwxr-xr-x  23 root     root  4096 Jul 31 13:24 .
drwxr-xr-x  23 root     root  4096 Jul 31 13:24 ..
lrwxrwxrwx   1 root     root     7 Apr  3 08:00 bin -> usr/bin
drwxr-xr-x   3 root     root  4096 Jul  6 00:07 boot
drwxr-xr-x   2 root     root  4096 Jun 19 15:36 config
drwxr-xr-x  20 root     root  5080 Jul 29 19:12 dev
drwxr-xr-x 154 root     root 12288 Jul 30 22:34 etc
drwxr-xr-x   3 root     root  4096 Jun 18 17:09 home
dr-xr-xr-x   1 root     root     0 Jul 29 19:37 keybase
lrwxrwxrwx   1 root     root     7 Apr  3 08:00 lib -> usr/lib
lrwxrwxrwx   1 root     root     9 Apr  3 08:00 lib32 -> usr/lib32
lrwxrwxrwx   1 root     root     9 Apr  3 08:00 lib64 -> usr/lib64
lrwxrwxrwx   1 root     root    10 Apr  3 08:00 libx32 -> usr/libx32
drwx------   2 root     root 16384 Jun 18 17:01 lost+found
drwxr-xr-x   3 root     root  4096 Jun 18 17:11 media
drwxr-xr-x   2 root     root  4096 Apr  3 08:00 mnt
drwxr-xr-x   7 root     root  4096 Jul 15 22:42 opt
dr-xr-xr-x 412 root     root     0 Jul 29 19:12 proc
drwx------   8 root     root  4096 Dec 31  1969 recovery
drwx------   6 root     root  4096 Jul 31 13:23 root
drwxr-xr-x  37 root     root  1140 Jul 30 13:27 run
lrwxrwxrwx   1 root     root     8 Apr  3 08:00 sbin -> usr/sbin
drwxr-xr-x   6 root     root  4096 Jul 23 17:48 snap
drwxr-xr-x   2 root     root  4096 Apr  3 08:00 srv
drwxr-xr-x   9 konsumer root  4096 Jul 18 02:50 storage
dr-xr-xr-x  13 root     root     0 Jul 29 19:12 sys
lrwxrwxrwx   1 root     root     4 Jul 31 13:24 testlinkdir -> etc/
lrwxrwxrwx   1 root     root    15 Jul 31 13:24 testlinkfile -> etc/resolv.conf
drwxrwxrwt  30 root     root  4096 Jul 31 13:27 tmp
drwxr-xr-x  14 root     root  4096 Jun 17 12:49 usr
drwxr-xr-x  14 root     root  4096 Jul 23 17:46 var
```

**Comment by konsumer** [comment]
I think I still need to test on windows & osx, and test with a few different scenerios, but otherwise it seems to work.

```
luajit test.lua

bin/
boot/
config/
dev/
etc/
home/
keybase/
lib/
lib32/
lib64/
libx32/
lost+found/
media/
mnt/
opt/
proc/
recovery/
root/
run/
sbin/
snap/
srv/
storage/
sys/
testlinkdir/
tmp/
usr/
var/
testlinkfile
```

I wrapped `stat` and use that in `isDirectory` and `isFile` but I'm not sure if that will work on other OS's. Might be posix-only, and I should fallback to old method for windows.

**Comment by konsumer** [comment]
Ok, added lots of nice stat-related functions. need to double-check on Mac, and make sure windows-fallbacks work, but overall this seems right, now, at least for linux.

**Comment by konsumer** [comment]
Looks like the new `stat` stuff fails on OSX, so I will have a closer look.

**Comment by linux-man** [comment]
Right now, I'm on a RV with one solar panel and limited internet connection. I need some time.
I tested your changes on loveframes demo (Linux) and got an error about some s variable at a new function.

**Comment by konsumer** [comment]
Yeh, I'm still working on it. How about I close the PR, and make a new one when it's closer? It seems to be kind of a juggling act to get `stat` working on OSX & Linux, but I think it'll be cool.

**Pull request closed without merging**
